INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-02-19','1','6:30-9:30','lesson 1');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-02-21','1','6:30-9:30','lesson 2');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-02-24','1','10:00-2:00','lesson 3');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-02-26','2','6:30-9:30','lesson 4');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-02-28','2','6:30-9:30','lesson 5');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-03','2','10:00-2:00','lesson 6');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-05','3','6:30-9:30','lesson 7');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-07','3','6:30-9:30','lesson 8');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-10','3','10:00-2:00','lesson 9');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-12','4','6:30-9:30','lesson 10');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-14','4','6:30-9:30','lesson 11');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-17','4','10:00-2:00','lesson 12');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-19','5','6:30-9:30','lesson 13');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-21','5','6:30-9:30','lesson 14');
INSERT INTO bootcampspotV3.Lessons (date,week,time,title) values ('2018-03-24','5','10:00-2:00','lesson 15');

INSERT INTO bootcampspotV3.Homeworks (due,week,title) values ('2018-02-25','1','HTML');
INSERT INTO bootcampspotV3.Homeworks (due,week,title) values ('2018-03-04','2','HTML2');
INSERT INTO bootcampspotV3.Homeworks (due,week,title) values ('2018-03-11','3','CSS');
INSERT INTO bootcampspotV3.Homeworks (due,week,title) values ('2018-03-18','4','Bootstrap');
INSERT INTO bootcampspotV3.Homeworks (due,week,title) values ('2018-03-25','5','Javascript');

INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('1','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('1','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('1','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('1','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('1','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('2','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('2','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('2','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('2','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('2','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('3','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('3','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('3','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('3','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('3','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('4','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('4','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('4','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('4','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('4','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('5','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('5','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('5','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('5','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('5','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('6','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('6','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('6','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('6','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('6','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('7','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('7','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('7','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('7','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('7','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('8','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('8','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('8','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('8','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('8','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('9','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('9','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('9','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('9','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('9','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('10','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('10','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('10','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('10','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('10','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('11','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('11','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('11','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('11','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('11','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('12','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('12','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('12','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('12','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('12','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('13','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('13','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('13','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('13','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('13','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('14','5');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('15','1');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('15','2');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('15','3');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('15','4');
INSERT INTO bootcampspotV3.Attends (lesson_id,student_id) values ('15','5');

INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('1','1','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('2','1','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('3','1','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('4','1','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('5','1','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('1','2','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('2','2','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('3','2','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('4','2','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('5','2','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('1','3','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('2','3','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('3','3','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('4','3','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('5','3','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('1','4','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('2','4','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('3','4','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('4','4','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('5','4','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('1','5','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('2','5','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('3','5','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('4','5','{}');
INSERT INTO bootcampspotV3.Submits (student_id,homework_id,url) values ('5','5','{}');

